apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-java-app
  namespace: qa

spec:
  replicas: 2
  selector:
    matchLabels:
      app: three-tier-java-app

  template:
    metadata:
      labels:
        app: three-tier-java-app

    spec:
      containers:
        - name: three-tier-java-app
          image: 473488813390.dkr.ecr.ap-south-1.amazonaws.com/three-tier-java-app:3a2bc6d93b34d8484842ab9546afcc0b364f451e
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: appdb
            - name: DB_USER
              value: appuser
            - name: DB_PASSWORD
              value: apppassword
