apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-java-app
  namespace: qa

spec:
  replicas: 2
  selector:
    matchLabels:
      app: three-tier-java-app

  template:
    metadata:
      labels:
        app: three-tier-java-app

    spec:
      containers:
        - name: three-tier-java-app
          image: .dkr.ecr.ap-south-1.amazonaws.com/three-tier-java-app:16ab34e5caad4ac83b1c1cb04dd6545bcf110338
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: appdb
            - name: DB_USER
              value: appuser
            - name: DB_PASSWORD
              value: apppassword
