name: Three-Tier-App

on:
  push: 
    branches: 
      - main
  workflow_dispatch:


env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: three-tier-java-app
  EKS_CLUSTER_NAME: my-cluster
  IMAGE_TAG: ${{ github.sha }}

jobs:
# ============================================================
  # 1. BUILD + TEST
  # ============================================================

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: build application
        run: |
          mvn clean package -DskipTests=false

      - name: verify war file
        run: |
          ls -lh target/
          find target -name "*,war"
          
      
  sonarqube:
    name: sonarqube analysis
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=three-tier-java-app \
            -Dsonar.projectName=three-tier-java-app \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN

        

      # ============================================================
  # 3. DOCKER BUILD + ECR PUSH
  # ============================================================
  docker:
    name: Build Docker Image and Push to ECR
    runs-on: ubuntu-latest
    needs:
      - build
      - sonarqube

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
  # --------------------------------------------------------
      # AWS authentication using GitHub OIDC
      # --------------------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS
        run: aws sts get-caller-identity
          
        
